{{- if .Values.ingress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "velocity.ingress.name" . }}
  labels:
    app: {{ template "velocity.ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.url.domain }}
      http:
        paths:
          - path: /velocity
            backend:
              serviceName: {{ template "velocity.ui.name" . }}
              servicePort: {{ .Values.ui.service.externalPort }}
          - path: /velocity-consumer
            backend:
              serviceName: {{ template "velocity.consumer.name" . }}
              servicePort: {{ .Values.consumer.service.externalPort }}
{{- end -}}
