apiVersion: v1
kind: Service
metadata:
  name: {{ template "velocity.consumer.name" . }}
  labels:
    app: {{ template "velocity.consumer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.consumer.service.type }}
  ports:
    - port: {{ .Values.consumer.service.externalPort }}
      targetPort: 6004
      protocol: TCP
      name: consumer-port
  selector:
    app: {{ template "velocity.consumer.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "velocity.ui.name" . }}
  labels:
    app: {{ template "velocity.ui.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.externalPort }}
      targetPort: 80
      protocol: TCP
      name: ui-port
  selector:
    app: {{ template "velocity.ui.name" . }}
    release: {{ .Release.Name }}
